#!/usr/bin/env python3
"""Generate uBlock Origin filter lists from word data + source templates.

Source of truth:
  words/<region>.yml     terms grouped by category, each tagged with a tier (1-3)
  sources/<site>.yml     per-site filter template using the {TERMS} placeholder
  site-rules/<site>.yml  raw site-specific filters (subreddits, etc.), tier-tagged

Output (committed, subscribable):
  dist/<region>-1.txt    tier 1 only        (fewest false positives)
  dist/<region>-2.txt    tier 2 only
  dist/<region>-3.txt    tier 3 only
  dist/<region>.txt      all tiers (master, self-contained)

Run:  uv run python scripts/generate.py [--check]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
WORDS_DIR = ROOT / "words"
SOURCES_DIR = ROOT / "sources"
SITE_RULES_DIR = ROOT / "site-rules"
DIST_DIR = ROOT / "dist"

VALID_TIERS = (1, 2, 3, 4)
PLACEHOLDER = "{TERMS}"
FLAGS_PH = "{FLAGS}"


def load_yaml(path: Path):
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def normalize_terms(category: dict) -> list[dict]:
    default_tier = category.get("default_tier", 1)
    terms: list[dict] = []
    for entry in category.get("terms", []) or []:
        if isinstance(entry, str):
            terms.append({"value": entry, "is_pattern": False,
                          "tier": default_tier, "cs": False})
        elif isinstance(entry, dict) and "pattern" in entry:
            terms.append({"value": entry["pattern"], "is_pattern": True,
                          "tier": entry.get("tier", default_tier),
                          "cs": entry.get("cs", False)})
        elif isinstance(entry, dict) and "term" in entry:
            terms.append({"value": entry["term"], "is_pattern": False,
                          "tier": entry.get("tier", default_tier),
                          "cs": entry.get("cs", False)})
        else:
            raise ValueError(f"category {category.get('id')!r}: bad term entry {entry!r}")
    return terms


def fragment(term: dict) -> str:
    return term["value"] if term["is_pattern"] else re.escape(term["value"])


def load_sources() -> list[dict]:
    sources = [load_yaml(p) for p in sorted(SOURCES_DIR.glob("*.yml"))]
    for src in sources:
        for placeholder in (PLACEHOLDER, FLAGS_PH):
            if placeholder not in src["template"]:
                raise ValueError(f"source {src['id']!r}: template missing {placeholder}")
    return sources


def load_site_rules() -> dict[str, list[dict]]:
    rules: dict[str, list[dict]] = {}
    for path in sorted(SITE_RULES_DIR.glob("*.yml")):
        data = load_yaml(path)
        rules[data["id"]] = data.get("rules", []) or []
    return rules


def render(region_data: dict, sources: list[dict],
           site_rules: dict[str, list[dict]], tiers: set[int], suffix: str) -> str:
    meta = region_data["meta"]
    title = f"{meta['title']} — {suffix}" if suffix else meta["title"]
    out = ["[uBlock Origin 1.0]",
           f"! Title: {title}",
           f"! Description: {meta['description']}"]
    if meta.get("expires"):
        out.append(f"! Expires: {meta['expires']}")
    out.append("! Generated by scripts/generate.py — DO NOT EDIT.")
    out.append(f"! Edit words/{meta['region']}.yml, then: uv run python scripts/generate.py")

    for src in sources:
        for cat in region_data["categories"]:
            terms = [t for t in normalize_terms(cat) if t["tier"] in tiers]
            if not terms:
                continue
            out += ["", f"! --- {src['name']}: {cat['name']} ---"]
            if cat.get("description"):
                out.append(f"! {cat['description']}")
            # Case-sensitive terms (e.g. all-caps "US", "PC") get their own line
            # without the /i flag; everything else stays case-insensitive.
            insensitive = [t for t in terms if not t["cs"]]
            sensitive = [t for t in terms if t["cs"]]
            for subset, flags in ((insensitive, "i"), (sensitive, "")):
                if not subset:
                    continue
                body = "|".join(fragment(t) for t in subset)
                out.append(src["template"].replace(PLACEHOLDER, body).replace(FLAGS_PH, flags))
        applicable = [r for r in site_rules.get(src["id"], []) if r["tier"] in tiers]
        if applicable:
            out += ["", f"! --- {src['name']}: site-specific ---"]
            for rule in applicable:
                if rule.get("note"):
                    out.append(f"! {rule['note']}")
                out.append(rule["filter"])
    return "\n".join(out) + "\n"


def build_outputs() -> dict[Path, str]:
    sources = load_sources()
    site_rules = load_site_rules()
    files: dict[Path, str] = {}
    for region_path in sorted(WORDS_DIR.glob("*.yml")):
        data = load_yaml(region_path)
        region = data["meta"]["region"]
        for tier in VALID_TIERS:
            files[DIST_DIR / f"{region}-{tier}.txt"] = render(
                data, sources, site_rules, {tier}, f"Tier {tier}")
        files[DIST_DIR / f"{region}.txt"] = render(
            data, sources, site_rules, set(VALID_TIERS), "All tiers")
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate uBlock filter lists.")
    parser.add_argument("--check", action="store_true",
                        help="fail if committed dist/ differs from a fresh build")
    args = parser.parse_args()

    files = build_outputs()

    if args.check:
        stale = [p for p, content in files.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != content]
        if stale:
            print("dist/ is out of date. Run: uv run python scripts/generate.py")
            for path in sorted(stale):
                print(f"  stale: {path.relative_to(ROOT)}")
            return 1
        print(f"dist/ up to date ({len(files)} files).")
        return 0

    DIST_DIR.mkdir(exist_ok=True)
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(files)} files to {DIST_DIR.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
